baseURL = 'https://jay645.xyz/'
languageCode = 'en-us'
title = 'Jay645'
copyright = 'Jay Sung'
enableRobotsTXT = true

[module]
  [[module.imports]]
    path = "github.com/michenriksen/hugo-theme-til"

[outputs]
  home = ['html']
  section = ['html', 'rss', 'json']
  page = ['html']

[menus]
  [[menus.main]]
    name = 'Notes'
    pageRef = '/notes'
    weight = 20
  [[menus.main]]
    name = 'Posts'
    pageRef = '/posts'
    weight = 30
  [[menus.main]]
    name = 'Graph'
    pageRef = '/graph'
    weight = 40

[markup]
  [markup.highlight]
    noClasses = false
    style = 'tokyonight-night'

  [markup.goldmark]
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true

[params]
  [params.author]
    name = 'Jay Sung'
    email = 'jaysung645@gmail.com'

  [params.home]
    # Display recent blog posts on the homepage.
    # Default: true
    showRecentPosts = true

    # Set how many recent blog posts to show.
    # Default: 3
    recentPostsLimit = 3

    # Display recent notes on the homepage.
    # Default: true
    showRecentNotes = true

    # Set how many recent notes to show.
    # Default: 5
    recentNotesLimit = 5
     
  [params.notes]
    # Set the number of notes to list on each page.
    # Default: 20
    pageSize = 20

    # Show a filter option for note categories above the notes list.
    # Default: true
    showCategoryFilter = true

  # Footer setup
  [params.footer]
    # Specify the Creative Commons license to apply to your content.
    # Options: `by`, `by_sa`, `by_nc`, `by_nc_sa`, `by_nd`, `by_nc_nd`, `zero`, `none`
    # Learn more at https://creativecommons.org/share-your-work/cclicenses/
    # Default: none
    creativeCommonsLicense = 'none'

    # Show Creative Commons icons for the selected license.
    # Default: true
    showCreativeCommonsIcons = true

    # Show a credit link to the Today I Learned theme in the footer.
    # Default: true
    showThemeCredit = true

  [params.robotstxt]
    blockCC = true
    blockAI = true
